import { CodeBlock } from '@/app/components/CodeBlock';
import { PageFooterNav } from '@/app/components/PageFooterNav';
import React from 'react';

export default function SettlementsReceipts() {
  return (
    <>
      <h5>Integration Guides</h5>
      <h1>Settlements & Receipts</h1>
      <p className="lead">
        Once a payment is completed, the <strong>x402 Facilitator</strong>{' '}
        provides a verifiable settlement record — known as a <em>receipt</em> —
        that both Buyer and Seller can use to confirm that the transaction has
        been finalized.
      </p>

      <br />
      <h2 id="understanding-settlements">Understanding Settlements</h2>
      <p>
        A settlement represents the point at which funds have been successfully
        transferred or cryptographically verified between a Buyer and Seller.
        The Facilitator coordinates this process across supported networks and
        ensures that receipts can be independently validated.
      </p>

      <ul>
        <li>On-chain settlements confirm via transaction hash</li>
        <li>Off-chain or hybrid settlements confirm via signature</li>
        <li>Receipts can always be re-verified via the Facilitator API</li>
      </ul>

      <br />
      <h2 id="receipt-format">Receipt Format</h2>
      <p>
        Every completed payment session produces a JSON-formatted receipt
        returned by the Facilitator. Here’s a typical example:
      </p>
      <CodeBlock language="json">{`{
  "sessionId": "sess_abc123",
  "status": "completed",
  "network": "base",
  "txHash": "0x123abc...",
  "payer": "0xBuyerAddress",
  "amount": "0.001",
  "currency": "ETH",
  "timestamp": "2025-10-30T14:15:00Z",
  "signature": "0xFacilitatorSignedProof"
}`}</CodeBlock>
      <p>
        The <code>signature</code> field is generated by the Facilitator and can
        be used to verify authenticity. The Buyer or Seller can independently
        confirm its validity using the Facilitator’s public key.
      </p>

      <br />
      <h2 id="retrieving-receipts">Retrieving Receipts</h2>
      <p>
        You can retrieve receipts at any time using the <code>/verify</code>{' '}
        endpoint:
      </p>
      <pre>
        <code>{`GET https://facilitator.x402.io/api/payment/verify?sessionId=sess_abc123`}</code>
      </pre>
      <p>
        If the payment is settled, the response will include the receipt object.
        Otherwise, you’ll receive a status like <code>pending</code> or{' '}
        <code>expired</code>.
      </p>

      <br />
      <h2 id="verification-flow-server">Example Verification Flow (Server)</h2>
      <CodeBlock language="ts">{`import fetch from "node-fetch";

async function verify(sessionId) {
  const response = await fetch(
    \`https://facilitator.x402.io/api/payment/verify?sessionId=\${sessionId}\`
  );
  const data = await response.json();

  if (data.status === "completed") {
    console.log("Payment verified:", data);
  } else {
    console.log("Payment not settled:", data.status);
  }
}`}</CodeBlock>

      <br />
      <h2 id="verification-flow-client">Example Verification Flow (Client)</h2>
      <CodeBlock language="ts">{`import { X402 } from "@x402/sdk";

const client = new X402();

const receipt = await client.verify("sess_abc123");

if (receipt.status === "completed") {
  console.log("Payment confirmed", receipt);
}`}</CodeBlock>

      <br />
      <h2 id="reconciliation-and-logging">Reconciliation and Logging</h2>
      <p>
        Sellers can log receipts for audit or compliance purposes. A recommended
        approach is to store the <code>sessionId</code>, <code>txHash</code>,
        and <code>signature</code> fields in a local database. These can later
        be reconciled against Facilitator or on-chain records.
      </p>

      <CodeBlock language="json">{`{
  "sessionId": "sess_abc123",
  "status": "completed",
  "txHash": "0x123abc...",
  "amount": "0.001",
  "currency": "ETH",
  "payer": "0xBuyerAddress",
  "verified": true
}`}</CodeBlock>

      <br />
      <h2 id="public-key-verification">Public Key Verification</h2>
      <p>
        Each receipt is signed by the x402 Facilitator. The public key used to
        verify these receipts is available at:
      </p>
      <pre>
        <code>{`GET https://facilitator.x402.io/api/public-key`}</code>
      </pre>
      <p>
        Developers can verify receipt authenticity using any ECDSA-compatible
        library (e.g. ethers.js, web3.py) to confirm that the{' '}
        <code>signature</code> matches the receipt content.
      </p>

      <br />
      <h2 id="failed-or-disputed-payments">
        Handling Failed or Disputed Payments
      </h2>
      <p>
        If a session reports <code>failed</code> or <code>disputed</code>,
        applications should log the session details and optionally notify the
        Buyer to retry. The Facilitator maintains a record of every attempted
        transaction and can expose dispute-resolution metadata if needed.
      </p>

      <br />
      <h2 id="next-steps">Next Steps</h2>
      <p>
        With settlement handling complete, you’ve fully integrated x402 — from
        session creation to verified payment receipts. You can now explore the
        upcoming <strong>tooling layer</strong> for analytics, dashboards, and
        ecosystem extensions.
      </p>

      <PageFooterNav
        prev={{
          title: 'Testing Sandbox',
          href: '/docs/integration/testing-sandbox',
        }}
        nextGroup={{
          title: 'Ecosystem & Tooling',
          href: '/docs/tooling/overview',
        }}
        prevGroup={{
          title: 'Core Concepts',
          href: '/docs/core-concepts/network-support',
        }}
      />
    </>
  );
}
